# 注意：value 是 base64 编码后的内容
# echo -n "demo" | base64      → ZGVtbw==
# echo -n "demo123" | base64   → ZGVtbzEyMw==
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: k8s-demo
  labels:
    app: k8s-local-stack
type: Opaque
data:
  db-user: ZGVtbw==
  db-password: ZGVtbzEyMw==