apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-local-stack-deploy
  namespace: k8s-demo
  labels:
    app: k8s-local-stack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-local-stack
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: k8s-local-stack
        tier: backend
    spec:
      containers:
      - name: app
        image: k8s-local-stack:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: APP_NAME
          value: "k8s-local-stack"
        envFrom:
        # 整 ConfigMap 注入为环境变量
        - configMapRef:
            name: app-config
        # 整 Secret 注入为环境变量
        - secretRef:
            name: app-secret
        volumeMounts:
        # 挂载 ConfigMap 中的 app.yaml
        - name: config-vol
          mountPath: /etc/config
          readOnly: true
        # 挂载 Secret
        - name: secret-vol
          mountPath: /etc/secret
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 12        # 60s 内未就绪不算失败
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config-vol
        configMap:
          name: app-config
      - name: secret-vol
        secret:
          secretName: app-secret